-- Overrides for the built-in schema defaults (settings.lua). Read in two cases: for a brand-new
-- save -- one that has never had this mod's settings saved into it before -- and again whenever
-- the player presses "Reset section" or "Reset everything" in the settings window, since both
-- restore what a new save would start with (see engine.lua's resetSection/resetAll handlers).
--
-- Paths mirror the dotted settings paths used everywhere else (settings.get/settings.set), so a
-- setting here is written the same way it would show up in a saved game, for example:
--
--   patterns = { default = "{type} {towns:3}[ {n}]" },
--   scan = { linesPerTick = 10 },
--   defaults = { extraPrefixes = "Linie" },
--
-- A value that does not match its schema row (wrong type, out of range, not one of an enum's
-- choices) is silently ignored and the shipped default is used instead -- see settings.merge().
--
-- install.sh overwrites the copy of this file inside the installed mod folder every time it
-- runs, so edit the copy in this repository, not the one under Steam's local mods directory.
return {
    -- patterns = { default = "{type} {towns:3}[ {n}]" },
    -- scan = { linesPerTick = 10 },
    -- defaults = { extraPrefixes = "Linie" },
}
